### ISSUE TITLE
Error getting video stream

### ISSUE THREAD

**Issue by navsgit** [comoc/TelloForUnity#1]
I'm using Unity 2018.1.5f1
When the project first loads, In Master scene, TelloVideo gameobject is missing two scripts and TelloBatteryStatus gameobject is missing one script.
I assigned TelloController and TelloVideoTexturel and TextUpdater to respective objects.
Now I'm able to control the drone no no video stream is showing.
Editor throws following error
Failed to load 'Assets/Plugins/x86_64/TelloVideoDecoder.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Any idea whats going on?
thansk

**Comment by comoc** [comment]
Hi,
Thank you for checking!

I rebuilt the DLL and added the prefab  so as not to loose the script reference.  
This is the commit id: 81be02e86fea0150eb124c411f16b5acd4d231e7
So could you try this one again?

Thanks,

**Comment by comoc** [comment]
I added TelloUnityDemo.unitypackage for easier creating new scene. in 8dbf1c21a4e4add6ef8b94c8c5ac163dd2ef3d1b

**Comment by navsgit** [comment]
Thanks for your response, I downloaded the project and loaded in Unity, it didn't work same error, but then I tried the unitypackage file, and now no error. However still no video feed.
I think the problem might be Line 30 in Tello.cs file. The compiler show the event onVideoData is never used.
Do i need to run ffmpeg from cmd prompt or anything like that?

**Comment by comoc** [comment]
Thank you for trying!

I've forgotten to include *.meta files into the repository. Now the problem was fixed.

The video data is received and processed by the TelloVideoDecoder.dll. So we do not need handle the onVideoData.
Please double-check the firewall settings of your Unity Editor.
**Public** network access is required to receive the Tello's video stream. But in most case, the default settings of it is only "Private". Because Unity Editor's installation process, user cannot choose the permission of public network access setting.

**Comment by joshferns** [comment]
Hi @comoc  Thank so much for this plugin.
I am not able to get the video stream.
I enabled public and private access to the Untiy Editor in the firewall settings.
Battery status etc shows up.
Are there any steps I could take in order to debug?

Unity version 2018.1.5. OS Windows 10.

Thanks.

**Comment by joshferns** [comment]
Update 2: 
I got it working.. **had to turn off my firewall completely**..
not really sure why this was needed.
I originally followed the steps along the lines of [https://www.dummies.com/computers/operating-systems/windows-7/how-to-allow-programs-through-the-windows-7-firewall/](url)
but apparently that still wasn't enough.

I have multiple versions of unity, maybe that messed things up
If anyone can point out my mistake I'll be really thankful.

**Comment by comoc** [comment]
Hi @joshferns ,

Could you try to modify the "Inbound Rules" of your Unity Editor like this picture.
![image](https://user-images.githubusercontent.com/843396/44824427-6eb46280-ac40-11e8-8056-af898496b1d0.png)

Thanks,

**Comment by carter-james89** [comment]
This fixed it for me, thanks a lot. Turning the firewall off and on was super annoying.

**Comment by joshferns** [comment]
@comoc  success, it worked!
I had no idea about this option.
Thank you so much.

**Comment by comoc** [comment]
I am happy to hear that!
