### ISSUE TITLE
How to build TelloVideoDecoder dll

### ISSUE THREAD

**Issue by joshferns** [comoc/TelloForUnity#2]
Hi @comoc could you please provide instructions on how to build the TelloVideoDecoder.dll
Does ffmpeg need to be built separately, if not, could you point to the files used. 
I eventually got stuck at libavutil/avconfig.h not found during the build process in Visual Studio

**Comment by comoc** [comment]
Hi @joshferns,
In my case, I followed this document to build and install FFmpeg 64 bit version separately.
https://www.ffmpeg.org/platform.html#Native-Windows-compilation-using-MinGW-or-MinGW_002dw64
And you will need to choose the target platform as **x64** in Visual Studio.
![image](https://user-images.githubusercontent.com/843396/44317495-8b94ad00-a46c-11e8-944d-e3cb84c32892.png)
Thank you,

**Comment by joshferns** [comment]
Thanks for this.
